### ISSUE TITLE
Typos in Table 2 for D4RL baselines numbers

### ISSUE THREAD

**Issue by MarcCote** [machelreid/can-wikipedia-help-offline-rl#1]
Hi, I believe there are some typos in the number reported from https://arxiv.org/abs/2004.07219 in Table 2 of your paper. In particular, for hopper and walker2d -medium-expert: the BC numbers don't match those reported in https://arxiv.org/abs/2004.07219 and the CQL numbers have been swapped.

**Comment by machelreid** [comment]
Thanks for pointing this out, we'll make changes in revision!
